// Auto-generated by OpenLane
module clb(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input ff_en,
  input[3:0] I,
  input cin,
  output O,
  output cout
);
endmodule
