/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module clb(clk, rst, ff_en, I, cin, O, cout);
  input [3:0] I;
  wire [3:0] I;
  output O;
  wire O;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output cout;
  wire cout;
  input ff_en;
  wire ff_en;
  input rst;
  wire rst;
  sky130_fd_sc_hd__and2_2 _0_ (
    .A(I[3]),
    .B(cin),
    .X(cout)
  );
  sky130_fd_sc_hd__conb_1 _1_ (
    .LO(O)
  );
endmodule
