// Auto-generated by OpenLane
module nano_cpu(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input reset,
  input[7:0] instruction,
  output[7:0] pc,
  output[7:0] out_port
);
endmodule
