// Auto-generated by OpenLane
module control_unit(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input start,
  output busy,
  output done,
  output[1:0] state_out
);
endmodule
