/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module nano_cpu(clk, reset, instruction, pc, out_port);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire \acc[0] ;
  wire \acc[1] ;
  wire \acc[2] ;
  wire \acc[3] ;
  wire \acc[4] ;
  wire \acc[5] ;
  wire \acc[6] ;
  wire \acc[7] ;
  input clk;
  wire clk;
  input [7:0] instruction;
  wire [7:0] instruction;
  output [7:0] out_port;
  wire [7:0] out_port;
  output [7:0] pc;
  wire [7:0] pc;
  input reset;
  wire reset;
  wire state;
  sky130_fd_sc_hd__nand2_2 _130_ (
    .A(instruction[5]),
    .B(_109_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__and2_2 _131_ (
    .A(_033_),
    .B(_035_),
    .X(_036_)
  );
  sky130_fd_sc_hd__nand2_2 _132_ (
    .A(_033_),
    .B(_035_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__o21a_2 _133_ (
    .A1(instruction[6]),
    .A2(_035_),
    .B1(\acc[0] ),
    .X(_038_)
  );
  sky130_fd_sc_hd__a21oi_2 _134_ (
    .A1(instruction[0]),
    .A2(_037_),
    .B1(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a31o_2 _135_ (
    .A1(instruction[0]),
    .A2(_037_),
    .A3(_038_),
    .B1(reset),
    .X(_040_)
  );
  sky130_fd_sc_hd__nor2_2 _136_ (
    .A(_039_),
    .B(_040_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand3b_2 _137_ (
    .A_N(instruction[7]),
    .B(instruction[6]),
    .C(instruction[5]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__and3_2 _138_ (
    .A(instruction[0]),
    .B(instruction[1]),
    .C(_041_),
    .X(_042_)
  );
  sky130_fd_sc_hd__a21oi_2 _139_ (
    .A1(instruction[0]),
    .A2(_041_),
    .B1(instruction[1]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__o21a_2 _140_ (
    .A1(_042_),
    .A2(_043_),
    .B1(\acc[1] ),
    .X(_044_)
  );
  sky130_fd_sc_hd__or3_2 _141_ (
    .A(\acc[1] ),
    .B(_042_),
    .C(_043_),
    .X(_045_)
  );
  sky130_fd_sc_hd__and2b_2 _142_ (
    .A_N(_044_),
    .B(_045_),
    .X(_046_)
  );
  sky130_fd_sc_hd__nand2b_2 _143_ (
    .A_N(\acc[0] ),
    .B(instruction[0]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__xor2_2 _144_ (
    .A(_046_),
    .B(_047_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _145_ (
    .A0(instruction[1]),
    .A1(_048_),
    .S(_032_),
    .X(_049_)
  );
  sky130_fd_sc_hd__or2_2 _146_ (
    .A(\acc[1] ),
    .B(_037_),
    .X(_050_)
  );
  sky130_fd_sc_hd__o211a_2 _147_ (
    .A1(_036_),
    .A2(_049_),
    .B1(_050_),
    .C1(_102_),
    .X(_018_)
  );
  sky130_fd_sc_hd__a21o_2 _148_ (
    .A1(_045_),
    .A2(_047_),
    .B1(_044_),
    .X(_051_)
  );
  sky130_fd_sc_hd__o21a_2 _149_ (
    .A1(instruction[0]),
    .A2(instruction[1]),
    .B1(_041_),
    .X(_052_)
  );
  sky130_fd_sc_hd__xnor2_2 _150_ (
    .A(instruction[2]),
    .B(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__xor2_2 _151_ (
    .A(\acc[2] ),
    .B(_053_),
    .X(_054_)
  );
  sky130_fd_sc_hd__and2_2 _152_ (
    .A(_051_),
    .B(_054_),
    .X(_055_)
  );
  sky130_fd_sc_hd__nor2_2 _153_ (
    .A(_051_),
    .B(_054_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nor2_2 _154_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__mux2_1 _155_ (
    .A0(instruction[2]),
    .A1(_057_),
    .S(_032_),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_1 _156_ (
    .A0(\acc[2] ),
    .A1(_058_),
    .S(_037_),
    .X(_059_)
  );
  sky130_fd_sc_hd__and2_2 _157_ (
    .A(_102_),
    .B(_059_),
    .X(_019_)
  );
  sky130_fd_sc_hd__or3_2 _158_ (
    .A(instruction[0]),
    .B(instruction[1]),
    .C(instruction[2]),
    .X(_060_)
  );
  sky130_fd_sc_hd__a21bo_2 _159_ (
    .A1(_041_),
    .A2(_060_),
    .B1_N(instruction[3]),
    .X(_061_)
  );
  sky130_fd_sc_hd__nand3b_2 _160_ (
    .A_N(instruction[3]),
    .B(_041_),
    .C(_060_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__and3_2 _161_ (
    .A(\acc[3] ),
    .B(_061_),
    .C(_062_),
    .X(_063_)
  );
  sky130_fd_sc_hd__a21o_2 _162_ (
    .A1(_061_),
    .A2(_062_),
    .B1(\acc[3] ),
    .X(_064_)
  );
  sky130_fd_sc_hd__and2b_2 _163_ (
    .A_N(_063_),
    .B(_064_),
    .X(_065_)
  );
  sky130_fd_sc_hd__a21oi_2 _164_ (
    .A1(\acc[2] ),
    .A2(_053_),
    .B1(_055_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__xor2_2 _165_ (
    .A(_065_),
    .B(_066_),
    .X(_067_)
  );
  sky130_fd_sc_hd__or3b_2 _166_ (
    .A(_035_),
    .B(instruction[6]),
    .C_N(instruction[3]),
    .X(_068_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _167_ (
    .A1_N(\acc[3] ),
    .A2_N(_036_),
    .B1(_067_),
    .B2(_033_),
    .X(_069_)
  );
  sky130_fd_sc_hd__a21oi_2 _168_ (
    .A1(_068_),
    .A2(_069_),
    .B1(reset),
    .Y(_020_)
  );
  sky130_fd_sc_hd__o21a_2 _169_ (
    .A1(instruction[3]),
    .A2(_060_),
    .B1(_041_),
    .X(_070_)
  );
  sky130_fd_sc_hd__xor2_2 _170_ (
    .A(instruction[4]),
    .B(_070_),
    .X(_071_)
  );
  sky130_fd_sc_hd__xnor2_2 _171_ (
    .A(\acc[4] ),
    .B(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a31o_2 _172_ (
    .A1(\acc[2] ),
    .A2(_053_),
    .A3(_064_),
    .B1(_063_),
    .X(_073_)
  );
  sky130_fd_sc_hd__a31o_2 _173_ (
    .A1(_051_),
    .A2(_054_),
    .A3(_065_),
    .B1(_073_),
    .X(_074_)
  );
  sky130_fd_sc_hd__xor2_2 _174_ (
    .A(_072_),
    .B(_074_),
    .X(_075_)
  );
  sky130_fd_sc_hd__mux2_1 _175_ (
    .A0(instruction[4]),
    .A1(_075_),
    .S(_032_),
    .X(_076_)
  );
  sky130_fd_sc_hd__mux2_1 _176_ (
    .A0(\acc[4] ),
    .A1(_076_),
    .S(_037_),
    .X(_077_)
  );
  sky130_fd_sc_hd__and2_2 _177_ (
    .A(_102_),
    .B(_077_),
    .X(_021_)
  );
  sky130_fd_sc_hd__o21ai_2 _178_ (
    .A1(instruction[4]),
    .A2(_070_),
    .B1(_041_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor2_2 _179_ (
    .A(\acc[5] ),
    .B(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2_2 _180_ (
    .A(\acc[5] ),
    .B(_078_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__and2b_2 _181_ (
    .A_N(_079_),
    .B(_080_),
    .X(_081_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _182_ (
    .A1_N(_099_),
    .A2_N(_071_),
    .B1(_072_),
    .B2(_074_),
    .X(_082_)
  );
  sky130_fd_sc_hd__xnor2_2 _183_ (
    .A(_081_),
    .B(_082_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _184_ (
    .A1_N(\acc[5] ),
    .A2_N(_036_),
    .B1(_083_),
    .B2(_033_),
    .X(_084_)
  );
  sky130_fd_sc_hd__nor2_2 _185_ (
    .A(reset),
    .B(_084_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__and2_2 _186_ (
    .A(\acc[6] ),
    .B(_078_),
    .X(_085_)
  );
  sky130_fd_sc_hd__or2_2 _187_ (
    .A(\acc[6] ),
    .B(_078_),
    .X(_086_)
  );
  sky130_fd_sc_hd__and2b_2 _188_ (
    .A_N(_085_),
    .B(_086_),
    .X(_087_)
  );
  sky130_fd_sc_hd__o31ai_2 _189_ (
    .A1(_099_),
    .A2(_071_),
    .A3(_079_),
    .B1(_080_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__a31o_2 _190_ (
    .A1(_072_),
    .A2(_074_),
    .A3(_081_),
    .B1(_088_),
    .X(_089_)
  );
  sky130_fd_sc_hd__xnor2_2 _191_ (
    .A(_087_),
    .B(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _192_ (
    .A1_N(\acc[6] ),
    .A2_N(_036_),
    .B1(_090_),
    .B2(_033_),
    .X(_091_)
  );
  sky130_fd_sc_hd__nor2_2 _193_ (
    .A(reset),
    .B(_091_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__and3_2 _194_ (
    .A(\acc[7] ),
    .B(_033_),
    .C(_035_),
    .X(_092_)
  );
  sky130_fd_sc_hd__a21oi_2 _195_ (
    .A1(_086_),
    .A2(_089_),
    .B1(_085_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor2_2 _196_ (
    .A(\acc[7] ),
    .B(_078_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__and2_2 _197_ (
    .A(\acc[7] ),
    .B(_078_),
    .X(_095_)
  );
  sky130_fd_sc_hd__nor2_2 _198_ (
    .A(_094_),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__a211o_2 _199_ (
    .A1(_087_),
    .A2(_089_),
    .B1(_096_),
    .C1(_085_),
    .X(_097_)
  );
  sky130_fd_sc_hd__o311a_2 _200_ (
    .A1(_093_),
    .A2(_094_),
    .A3(_095_),
    .B1(_097_),
    .C1(_034_),
    .X(_098_)
  );
  sky130_fd_sc_hd__o21a_2 _201_ (
    .A1(_092_),
    .A2(_098_),
    .B1(_102_),
    .X(_024_)
  );
  sky130_fd_sc_hd__inv_2 _202_ (
    .A(\acc[4] ),
    .Y(_099_)
  );
  sky130_fd_sc_hd__inv_2 _203_ (
    .A(pc[3]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__inv_2 _204_ (
    .A(pc[1]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__inv_2 _205_ (
    .A(reset),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2_2 _206_ (
    .A(state),
    .B(reset),
    .Y(_000_)
  );
  sky130_fd_sc_hd__or4_2 _207_ (
    .A(\acc[3] ),
    .B(\acc[2] ),
    .C(\acc[1] ),
    .D(\acc[0] ),
    .X(_103_)
  );
  sky130_fd_sc_hd__or4_2 _208_ (
    .A(\acc[7] ),
    .B(\acc[6] ),
    .C(\acc[5] ),
    .D(\acc[4] ),
    .X(_104_)
  );
  sky130_fd_sc_hd__o21ai_2 _209_ (
    .A1(_103_),
    .A2(_104_),
    .B1(instruction[5]),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand2b_2 _210_ (
    .A_N(instruction[5]),
    .B(instruction[6]),
    .Y(_106_)
  );
  sky130_fd_sc_hd__o211a_2 _211_ (
    .A1(instruction[6]),
    .A2(_105_),
    .B1(_106_),
    .C1(instruction[7]),
    .X(_107_)
  );
  sky130_fd_sc_hd__and2_2 _212_ (
    .A(instruction[0]),
    .B(_107_),
    .X(_108_)
  );
  sky130_fd_sc_hd__and2b_2 _213_ (
    .A_N(instruction[7]),
    .B(state),
    .X(_109_)
  );
  sky130_fd_sc_hd__nand2_2 _214_ (
    .A(instruction[6]),
    .B(instruction[5]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__a21o_2 _215_ (
    .A1(state),
    .A2(_110_),
    .B1(_109_),
    .X(_111_)
  );
  sky130_fd_sc_hd__and2_2 _216_ (
    .A(_107_),
    .B(_111_),
    .X(_112_)
  );
  sky130_fd_sc_hd__o21ai_2 _217_ (
    .A1(pc[0]),
    .A2(_107_),
    .B1(_111_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__o221a_2 _218_ (
    .A1(pc[0]),
    .A2(_111_),
    .B1(_113_),
    .B2(_108_),
    .C1(_102_),
    .X(_001_)
  );
  sky130_fd_sc_hd__and3_2 _219_ (
    .A(pc[1]),
    .B(pc[0]),
    .C(_111_),
    .X(_114_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _220_ (
    .A1_N(instruction[1]),
    .A2_N(_107_),
    .B1(_112_),
    .B2(_114_),
    .X(_115_)
  );
  sky130_fd_sc_hd__a211oi_2 _221_ (
    .A1(_101_),
    .A2(_113_),
    .B1(_115_),
    .C1(reset),
    .Y(_002_)
  );
  sky130_fd_sc_hd__a21oi_2 _222_ (
    .A1(pc[2]),
    .A2(_114_),
    .B1(_112_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a21o_2 _223_ (
    .A1(instruction[2]),
    .A2(_107_),
    .B1(_116_),
    .X(_117_)
  );
  sky130_fd_sc_hd__o311a_2 _224_ (
    .A1(pc[2]),
    .A2(_112_),
    .A3(_114_),
    .B1(_117_),
    .C1(_102_),
    .X(_003_)
  );
  sky130_fd_sc_hd__and3_2 _225_ (
    .A(pc[3]),
    .B(pc[2]),
    .C(_114_),
    .X(_118_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _226_ (
    .A1_N(instruction[3]),
    .A2_N(_107_),
    .B1(_112_),
    .B2(_118_),
    .X(_119_)
  );
  sky130_fd_sc_hd__a211oi_2 _227_ (
    .A1(_100_),
    .A2(_116_),
    .B1(_119_),
    .C1(reset),
    .Y(_004_)
  );
  sky130_fd_sc_hd__and2_2 _228_ (
    .A(pc[4]),
    .B(_118_),
    .X(_120_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _229_ (
    .A1_N(_112_),
    .A2_N(_120_),
    .B1(instruction[4]),
    .B2(_107_),
    .X(_121_)
  );
  sky130_fd_sc_hd__o311a_2 _230_ (
    .A1(pc[4]),
    .A2(_112_),
    .A3(_118_),
    .B1(_121_),
    .C1(_102_),
    .X(_005_)
  );
  sky130_fd_sc_hd__and3_2 _231_ (
    .A(pc[5]),
    .B(pc[4]),
    .C(_118_),
    .X(_122_)
  );
  sky130_fd_sc_hd__nor2_2 _232_ (
    .A(reset),
    .B(_112_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__o21ai_2 _233_ (
    .A1(pc[5]),
    .A2(_120_),
    .B1(_123_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nor2_2 _234_ (
    .A(_122_),
    .B(_124_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__and2_2 _235_ (
    .A(pc[6]),
    .B(_122_),
    .X(_125_)
  );
  sky130_fd_sc_hd__o21ai_2 _236_ (
    .A1(pc[6]),
    .A2(_122_),
    .B1(_123_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nor2_2 _237_ (
    .A(_125_),
    .B(_126_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__o21ai_2 _238_ (
    .A1(pc[7]),
    .A2(_107_),
    .B1(_125_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__o211a_2 _239_ (
    .A1(pc[7]),
    .A2(_125_),
    .B1(_127_),
    .C1(_123_),
    .X(_008_)
  );
  sky130_fd_sc_hd__and4b_2 _240_ (
    .A_N(instruction[5]),
    .B(state),
    .C(instruction[7]),
    .D(instruction[6]),
    .X(_128_)
  );
  sky130_fd_sc_hd__mux2_1 _241_ (
    .A0(out_port[0]),
    .A1(\acc[0] ),
    .S(_128_),
    .X(_129_)
  );
  sky130_fd_sc_hd__and2_2 _242_ (
    .A(_102_),
    .B(_129_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _243_ (
    .A0(out_port[1]),
    .A1(\acc[1] ),
    .S(_128_),
    .X(_025_)
  );
  sky130_fd_sc_hd__and2_2 _244_ (
    .A(_102_),
    .B(_025_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _245_ (
    .A0(out_port[2]),
    .A1(\acc[2] ),
    .S(_128_),
    .X(_026_)
  );
  sky130_fd_sc_hd__and2_2 _246_ (
    .A(_102_),
    .B(_026_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _247_ (
    .A0(out_port[3]),
    .A1(\acc[3] ),
    .S(_128_),
    .X(_027_)
  );
  sky130_fd_sc_hd__and2_2 _248_ (
    .A(_102_),
    .B(_027_),
    .X(_012_)
  );
  sky130_fd_sc_hd__nand2_2 _249_ (
    .A(_099_),
    .B(_128_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__o211a_2 _250_ (
    .A1(out_port[4]),
    .A2(_128_),
    .B1(_028_),
    .C1(_102_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _251_ (
    .A0(out_port[5]),
    .A1(\acc[5] ),
    .S(_128_),
    .X(_029_)
  );
  sky130_fd_sc_hd__and2_2 _252_ (
    .A(_102_),
    .B(_029_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _253_ (
    .A0(out_port[6]),
    .A1(\acc[6] ),
    .S(_128_),
    .X(_030_)
  );
  sky130_fd_sc_hd__and2_2 _254_ (
    .A(_102_),
    .B(_030_),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _255_ (
    .A0(out_port[7]),
    .A1(\acc[7] ),
    .S(_128_),
    .X(_031_)
  );
  sky130_fd_sc_hd__and2_2 _256_ (
    .A(_102_),
    .B(_031_),
    .X(_016_)
  );
  sky130_fd_sc_hd__and2b_2 _257_ (
    .A_N(instruction[7]),
    .B(instruction[6]),
    .X(_032_)
  );
  sky130_fd_sc_hd__nand2_2 _258_ (
    .A(state),
    .B(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__inv_2 _259_ (
    .A(_033_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__dfxtp_2 _260_ (
    .CLK(clk),
    .D(_000_),
    .Q(state)
  );
  sky130_fd_sc_hd__dfxtp_2 _261_ (
    .CLK(clk),
    .D(_001_),
    .Q(pc[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _262_ (
    .CLK(clk),
    .D(_002_),
    .Q(pc[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _263_ (
    .CLK(clk),
    .D(_003_),
    .Q(pc[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _264_ (
    .CLK(clk),
    .D(_004_),
    .Q(pc[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _265_ (
    .CLK(clk),
    .D(_005_),
    .Q(pc[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _266_ (
    .CLK(clk),
    .D(_006_),
    .Q(pc[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _267_ (
    .CLK(clk),
    .D(_007_),
    .Q(pc[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _268_ (
    .CLK(clk),
    .D(_008_),
    .Q(pc[7])
  );
  sky130_fd_sc_hd__dfxtp_2 _269_ (
    .CLK(clk),
    .D(_009_),
    .Q(out_port[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _270_ (
    .CLK(clk),
    .D(_010_),
    .Q(out_port[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _271_ (
    .CLK(clk),
    .D(_011_),
    .Q(out_port[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _272_ (
    .CLK(clk),
    .D(_012_),
    .Q(out_port[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _273_ (
    .CLK(clk),
    .D(_013_),
    .Q(out_port[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _274_ (
    .CLK(clk),
    .D(_014_),
    .Q(out_port[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _275_ (
    .CLK(clk),
    .D(_015_),
    .Q(out_port[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _276_ (
    .CLK(clk),
    .D(_016_),
    .Q(out_port[7])
  );
  sky130_fd_sc_hd__dfxtp_2 _277_ (
    .CLK(clk),
    .D(_017_),
    .Q(\acc[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _278_ (
    .CLK(clk),
    .D(_018_),
    .Q(\acc[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _279_ (
    .CLK(clk),
    .D(_019_),
    .Q(\acc[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _280_ (
    .CLK(clk),
    .D(_020_),
    .Q(\acc[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _281_ (
    .CLK(clk),
    .D(_021_),
    .Q(\acc[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _282_ (
    .CLK(clk),
    .D(_022_),
    .Q(\acc[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _283_ (
    .CLK(clk),
    .D(_023_),
    .Q(\acc[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _284_ (
    .CLK(clk),
    .D(_024_),
    .Q(\acc[7] )
  );
endmodule
